source 'https://rubygems.org'

gem 'rspec'
gem 'capybara'
gem 'selenium-webdriver'
gem 'syntax'
gem 'cuke_sniffer'
gem 'cucumber'
gem 'cucumber-core'
gem 'parallel_tests'
gem 'rake'
gem 'yard'
gem 'chromedriver-helper'
gem 'rest-client'
gem 'appium_capybara'